#+title: Generaldomo

This package holds the [[http://zguide.zeromq.org/py:all#Asynchronous-Majordomo-Pattern][Majordomo]] examples from the ZeroMQ Zguide which
have been generalized to so the broker uses either the original ROUTER
or a SERVER socket.  It also collects the code into a Python package
and provides a unified command line interface.

The Majordomo examples are copied to [[file:md/][md/]] for reference.

* Install

#+begin_example
  $ python3 -m venv /path/to/venv
  $ source /path/to/venv/bin/activate
  $ pip install --pre pyzmq \
      --install-option=--enable-drafts \
      --install-option=--zmq=/path/to/zmq
  $ pip install -r requirements.txt
  $ pip install [-e] .
#+end_example

* Use

All example programs are exposed through a common ~generaldomo~ CLI.

  #+begin_export 
  $ generaldomo --help  
  #+end_export

The simple, self-contained "tripping" example with one or the other
"serverish" socket type:

#+begin_example
  $ generaldomo tripping -n 1000 -f router -b router
  $ generaldomo tripping -n 1000 -f server -b server
#+end_example

To run the full Majordomo example, run each in three terminals:

#+begin_example
$ generaldomo broker --verbose -s server
$ generaldomo echo --verbose -s client
$ generaldomo client --verbose -n 2 -s client echo hello world
#+end_example

Likewise this trio can be run with the ROUTER/DEALER socket types.
The ~broker~ taking ~-s router~ with ~echo~ and ~client~ taking ~-s dealer~.

* Discussion

This package is not particularly useful for anything practical except
learning.  It was written to understand the broken symmetry between
the ROUTER/DEALER pair and the SERVER/CLIENT pair.  

In the modified version of copy of [[file:generaldomo/zhelpers.py][zhelpers.py]] there are "serverish"
and "clientish" functions that wrap send/recv which perform type
erasure between the two pairs of sockets.  These four functions embody
what is needed to support Majordomo protocol with the new
SERVER/CLIENT sockets.  



